# Generated by Django 5.0 on 2023-12-11 20:42

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='path/to/default/image.jpg', upload_to=''),
        ),
    ]
